--- #YAML:1.0
name:               textrender
version:            1.08
abstract:           Turn stdin into rendered text graphics.
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::File:          2.04
    Carp:                 1
    Cwd:                  3
    Exporter:             5
    Getopt::Std::Strict:  1.01
    Smart::Comments:      1
    String::ShellQuote:   1.03
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
